---
title: "JSDM model test"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(arm)
library(jagsUI)
library(ggplot2)
library(gridExtra)
library(parallel)
library(Rcpp)
library(magrittr)
library(purrr)
library(readr)

setwd("~/Desktop/VirtualCommunity/simcoms-master/ExampleFiles")
lapply(list.files(path = "."),load,.GlobalEnv)

```


Data was simulated using VirtualCommunity code.
Model was fitted using JAGS 

```{r load_m}

load("model-2019-04-09-19-02-16.rda")
summary(model)
model$Rhat
model$n.eff
model$mcmc.info[1:7]
```

##Test

Plots

```{r draw, echo=FALSE}
setwd("~/Desktop/VirtualCommunity/simcoms-master/")
sim_data<-readRDS("sim_data.rds")

#' Extract correlation parameter means
#+ mean-correlations

prob_cooccur_es <- function(Y) {
  K <- ncol(Y)
  ans <- matrix(0, K, K)
  
  for (k in 1:K) {
    for (kk in 1:K) {
      N1 <- sum(Y[, k])
      N2 <- sum(Y[, kk])
      N <- nrow(Y)
      j <- max(0, N1 + N2 - N):min(N1, N2)
      p <- vector("numeric", length(j))
      for (i in seq_along(j)) {
        p[i] <- (
          choose(N, j[i]) * choose(N - j[i], N2 - j[i]) *
            choose(N - N2, N1 - j[i])
        ) / (
          choose(N, N2) * choose(N, N1)
        )
      }  
      ans[k, kk] <- (sum(Y[, k] + Y[, kk] == 2) - sum(p * j)) / N
    }
  }
  ans
}

models<-list(EnvEvenSp5=model)
mean_correlations <- do.call(
  rbind,
  lapply(
    seq_along(models),
    function(i) {
      x <- models[[i]]
      nm <- strsplit(
        names(models)[[i]], "(?<=[a-z])(?=[A-Z])", perl = TRUE
      )[[1]]
      nsp <- ncol(x$mean$Rho)
      ut <- upper.tri(x$mean$Rho)
      sp <- arrayInd(which(ut), c(nsp, nsp))
      ans <- data.frame(
        model = i,
        sp1 = sp[, 1],
        sp2 = sp[, 2],
        rho = c(prob_cooccur_es(x$model$cluster1$data()$Y)[ut], x$mean$Rho[ut]),
        rho_type = rep(c("Effect-Size", "Residual"), each = sum(ut)),
        sgn = sign(x$mean$Rho)[ut],
        significant = x$overlap$Rho[ut],
        #cint = simulation_parameters$comp_inter[[i]][ut],
        #fint = simulation_parameters$fac_inter[[i]][ut],
        cint = comp_inter[[i]][ut],
        fint = fac_inter[[i]][ut],
        density = tail(nm, 2)[1],
        type = paste0(head(nm, -2), collapse = ""),
        nsp = nsp,
        stringsAsFactors = FALSE
      )
      ans$cint[is.na(ans$cint)] <- 0
      ans$fint[is.na(ans$fint)] <- 0
      ans$density[ans$density == "Even"] <- "None"
      ans$density <- factor(ans$density, c("None", "Sparse", "Dense"))
      ans$type[ans$type == "Env"] <- "Environmental\nFiltering Only"
      ans$type[ans$type == "Fac"] <- "Facilitation"
      ans$type[ans$type == "Comp"] <- "Competition"
      ans$type[ans$type == "FacComp"] <- "Facililation +\nCompetition"
      ans$type <- factor(
        ans$type, 
        c(
          "Environmental\nFiltering Only", "Facilitation", "Competition",
          "Facililation +\nCompetition"
        )
      )
      ans$interaction <- "None"
      ans$interaction <- ifelse(ans$cint, "Competition", ans$interaction)
      ans$interaction <- ifelse(ans$fint, "Facilitation", ans$interaction)
      ans$status <- ifelse(
        ans$significant,
        ifelse(ans$sgn * -ans$cint == 1 | ans$sgn * ans$fint == 1, "TP", "FP"),
        ifelse(ans$cint == 0 & ans$fint == 0, "TN", "FN")
      )
      ans$interaction <- factor(
        ans$interaction, c("None", "Facilitation", "Competition")
      )
      ans
    }
  )
)

x <- subset(mean_correlations, type != "Environmental\nFiltering Only")
acc <- by(x, x$model, function(x) sum(x$status == "TP" | x$status == "TN") / nrow(x))

#' Plot correlation parameter means
#+ plot-correlations
ggplot(mean_correlations) +
  aes(factor(nsp), rho, fill = interaction) +
  geom_hline(yintercept = 0) +
  geom_boxplot(
    outlier.size = .2, size = .1, position = position_dodge(preserve = "single")
  ) +
  scale_fill_manual(values = c("grey", "blue", "red")) +
  facet_grid(type ~ rho_type + density, switch = "y") +
  xlab("Number of species") +
  ylab("Correlation") +
  theme_bw() +
  theme(legend.position = "top")

```


```{r heat, include=FALSE}
data<-sim_data$EnvEvenSp5
data <- list(
  Y = subset(data, select = -env),
  X = cbind(1, scale(poly(data$env, 2))),
  covx = cov(cbind(1, scale(poly(data$env, 2)))),
  K = 3,
  J = ncol(data) - 1,
  n = nrow(data),
  I = diag(ncol(data) - 1),
  df = ncol(data)
)

Y_cor<-cor(data$Y) 
par(mfrow=c(1,3)) 
Yc <- heatmap(Y_cor, Rowv=NA, Colv=NA,scale="column")
R <- heatmap(model$mean$Rho, Rowv=NA, Colv=NA, scale="column")
E <- heatmap(model$mean$EnvRho, Rowv=NA, Colv=NA, scale="column")



```
